<?  $_SESSION['SESSION_PRODUCTID']="";
	$_SESSION['SESSION_QUANTITY']="";
	$_SESSION['SESSION_PRICE']="";
	$_SESSION['SESSION_PRODUCTTYPE']="";
	$_SESSION['Promocode_discount_id']="";
	$_SESSION['Promocode_discount']="";
	$_SESSION['discount']="";
	$_SESSION['Promocode_discountfrom']="";
	$_SESSION['total']="";
	$_SESSION['ShippingCharge']="";
	$_SESSION['finaltotal']="";
	$_SESSION['ShippingChargePercent']="";
	$_SESSION['ShippingMethoad']="";
	$_SESSION['SALES_TAX']="";
	$_SESSION['ShippingTax']="";
	$_SESSION['SESSION_handling_fee']="";
	$_SESSION['promocode']="";
	$_SESSION['promotype']="";
	$_SESSION['disctype']="";
	$_SESSION['discamt']="";
	$_SESSION['ShippingMethoadName']="";
	
	
	session_unregister('SESSION_PRODUCTID');
	session_unregister('SESSION_QUANTITY');
	session_unregister('SESSION_PRICE');
	session_unregister('SESSION_PRODUCTTYPE');
	session_unregister('Promocode_discount_id');
	session_unregister('Promocode_discount');
	session_unregister('discount');
	session_unregister('Promocode_discountfrom');
	session_unregister('total');
	session_unregister('ShippingCharge');
	session_unregister('finaltotal');
	session_unregister('ShippingChargePercent');
	session_unregister('ShippingMethoad');
	session_unregister('SALES_TAX');
	session_unregister('ShippingTax');
	session_unregister('SESSION_handling_fee');
	session_unregister('promocode');
	session_unregister('promotype');
	session_unregister('disctype');
	session_unregister('discamt');
	session_unregister('ShippingMethoadName');
	
	
	$_SESSION['cctype'] = "";
	$_SESSION['ccnumber'] = "";
	$_SESSION['ccmonth'] = "";
	$_SESSION['ccyear'] = "";
	$_SESSION['cvv'] = "";
	$_SESSION['ship_fname'] = "";
	$_SESSION['ship_lname'] = "";
	$_SESSION['ship_address1'] = "";
	$_SESSION['ship_address2'] = "";
	$_SESSION['ship_city'] = "";
	$_SESSION['ship_state'] = "";
	$_SESSION['ship_country'] = "";
	$_SESSION['ship_zipcode'] = "";
	$_SESSION['ship_day_telephone'] = "";
	$_SESSION['fname'] = "";
	$_SESSION['lname'] = "";
	$_SESSION['address1'] = "";
	$_SESSION['address2'] = "";
	$_SESSION['city'] = "";
	$_SESSION['state'] = "";
	$_SESSION['country'] = "";
	$_SESSION['zipcode'] = "";
	$_SESSION['day_telephone'] = "";

?>
